### ISSUE TITLE
SMS: Wittyflow

### ISSUE THREAD

**Issue by nyankahmensah** [aberba/ghana-apis#1]
Could you add wittyflow to the sms section

Homepage: https://wittyflow.com
Documentation: https://wittyflow.docs.apiary.io/#

**Comment by aberba** [comment]
I don't have experience with their service. Do you know how well it works?

**Comment by nyankahmensah** [comment]
4/5

their api doesnt support bulk messaging, but aside that, it good

**Comment by aberba** [comment]
Make a pull request and I'll merge and include that details
